import React, { createContext, useState } from "react";

export const DataContext = createContext();

export const DataProvider = (props) => {
  const [itemsList, setitemsList] = useState([
    {
      _id: "1",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },
    {
      _id: "2",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "20",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "123",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "3",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "4",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "5",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "6",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "7",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "8",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "9",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },
    {
      _id: "10",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "11",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "12",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "13",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "14",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "15",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "16",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "17",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "18",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },
  ]);

  const value = {
    itemsList: [itemsList, setitemsList],
  };
  const test = {
    itemsList: [itemsList, setitemsList],
  };

  return (
    <DataContext.Provider value={value} test={test}>
                  {props.children}       {" "}
    </DataContext.Provider>
  );
};
