import React, { createContext, useState } from "react";

export const DataContext = createContext();

export const DataProvider = (props) => {
  const [itemsList, setitemsList] = useState([
    {
      _id: "1",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(MacOS)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },
    {
      _id: "2",
      title: "HP Laptop",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Windows)" },
      ],
      images: "WinLaptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "HP", "IT", "COMPUTER", "WINDOWS"],
    },

    {
      _id: "3",
      title: "iPhone",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "iPhone",

      commonIssues: [
        { 1: "Broken Screen", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Device", type: "AI" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 13: "Touchscreen Issue", type: "TT" },
      ],
      tags: ["IPHONE", "APPLE", "IT", "MOBILE", "PHONE"],
    },

    {
      _id: "123",
      title: "Andorid Phone",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Samsung",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["SAMSUNG", "IT", "PHONE", "ANDROID","MOBILE"],
    },

    {
      _id: "543",
      title: "HP Printer",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "HpPrinter",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["PRINTER", "HP", "IT", "SCANNER"],
    },

    {
      _id: "4",
      title: "CCTV Investigation",
      department: "SEC",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "CCTV",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["CCTV", "SECURITY", "CAMERA", "SEC"],
    },

    {
      _id: "5",
      title: "Elevator",
      department: "MT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Elevator",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["ELEVATOR", "MT"],
    },

    {
      _id: "6",
      title: "HR Assistance",
      department: "HR",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "HR",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["HR", "HOLIDAY"],
    },

    {
      _id: "7",
      title: "Software Issue",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Software",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["SOFTWARE", "BUG", "IT", "WEB"],
    },

    {
      _id: "8",
      title: "User Account",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "User",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["USER", "ACCOUNT", "LOCKED", "COMPUTER"],
    },

    {
      _id: "9",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },
    {
      _id: "10",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "11",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "12",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "13",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "14",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "15",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "16",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "17",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },

    {
      _id: "18",
      title: "Macbook",
      department: "IT",
      DGI: [
        { Department: "IT-Support" },
        { Group: "User Devices" },
        { Item: "Laptop(Macbook)" },
      ],
      images: "Laptop",

      commonIssues: [
        { 1: "Broken Laptop", type: "TT" },
        { 2: "Software Issue", type: "TT" },
        { 3: "Request Laptop", type: "AI" },
        { 4: "Temporary Loan", type: "TT" },
        { 5: "Missing / Lost", type: "TT" },
        { 7: "Network / WiFi Issue", type: "TT" },
        { 8: "Hardware Issue", type: "TT" },
        { 9: "Battery Issue", type: "TT" },
        { 10: "Power Issue", type: "TT" },
        { 11: "Screen Issue", type: "TT" },
        { 12: "Keyboard Issue", type: "TT" },
        { 13: "Trackpad Issue", type: "TT" },
        { 14: "USB Issue", type: "TT" },
      ],
      tags: ["LAPTOP", "APPLE", "IT", "COMPUTER", "MACOS"],
    },
  ]);

  const value = {
    itemsList: [itemsList, setitemsList],
  };
  const test = {
    itemsList: [itemsList, setitemsList],
  };

  return (
    <DataContext.Provider value={value} test={test}>
                  {props.children}       {" "}
    </DataContext.Provider>
  );
};
